INSERT INTO TODO(ID, USERNAME,DESCRIPTION, TARGET_DATE, DONE)
VALUES(10001, 'souldeath', 'GET AWS Certified', CURRENT_DATE(), false);

INSERT INTO TODO(ID, USERNAME,DESCRIPTION, TARGET_DATE, DONE)
VALUES(10002, 'souldeath', 'GET Azure Certified', CURRENT_DATE(), false);

INSERT INTO TODO(ID, USERNAME,DESCRIPTION, TARGET_DATE, DONE)
VALUES(10003, 'souldeath', 'GET CGP Certified', CURRENT_DATE(), false);

INSERT INTO TODO(ID, USERNAME,DESCRIPTION, TARGET_DATE, DONE)
VALUES(10004, 'souldeath', 'Learn DevOps', CURRENT_DATE(), false);